name: strava_flutter
description: A Flutter Client for Strava V3 Api. Please note that this package has been rewritten sinve v1.2.2.
version: 3.3.0
homepage: https://github.com/dreampowder/strava_flutter

environment:
  sdk: ">=3.0.0 <3.10.5"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.5
  shared_preferences: ^2.0.9
  intl: ^0.19.0
  dio: ^5.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  device_apps: ^2.2.0
  uni_links2: ^0.6.0+2
  app_links: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: 1.5.3 # To launch some tests in /test

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
